/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package modelo;

/**
 *
 * @author Guest
 */
public class VtnaAddProd extends javax.swing.JFrame {

    /**
     * Creates new form VtnaAddProd
     */
    private Almacen almacen;
    
    /* 0 = producto basico, 1 = perecedero, 2 = no perecedero */
    
    private int tipoProducto = 0;
    
    public VtnaAddProd( Almacen almacen) {
        initComponents();
        this.almacen = almacen;
        cargarProveedores();
        setTitle("Proveedor");
        setLocationRelativeTo(null);
    }
    
    private void cargarProveedores() {
        selectProv.removeAllItems();
        for( int i = 0; i < this.almacen.cantidadProveedores(); ++i ) {
            Proveedor p = this.almacen.getProveedor(i);
            selectProv.addItem(p.getNombre());
        }
    }
    
    private void limpiarTipos() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectProv = new javax.swing.JComboBox<>();
        txtCodProd = new javax.swing.JTextField();
        txtDescProd = new javax.swing.JTextField();
        txtPrecioProd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Prod1 = new javax.swing.JRadioButton();
        Prod2 = new javax.swing.JRadioButton();
        Prod3 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        selectProv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectProvActionPerformed(evt);
            }
        });

        txtDescProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescProdActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo");

        jLabel2.setText("Descripcion");

        jLabel3.setText("Precio");

        Prod1.setSelected(true);
        Prod1.setText("Producto Basico");
        Prod1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Prod1ActionPerformed(evt);
            }
        });

        Prod2.setText("Producto Perecedero");
        Prod2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Prod2ActionPerformed(evt);
            }
        });

        Prod3.setText("Producto No Perecedero");
        Prod3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Prod3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Seleccione Proveedor");

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCodProd)
                                    .addComponent(txtDescProd)
                                    .addComponent(txtPrecioProd, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)))
                            .addComponent(selectProv, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Prod1)
                            .addComponent(Prod2)
                            .addComponent(Prod3)
                            .addComponent(jButton2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(183, 183, 183))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(Prod1))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(Prod2))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(Prod3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectProvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectProvActionPerformed

    private void txtDescProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescProdActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false); 
        // new Main().setVisible(true); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Prod1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Prod1ActionPerformed
        // TODO add your handling code here:
        Prod1.setEnabled(true);
        Prod2.setEnabled(false);
        Prod3.setEnabled(false);
        
        tipoProducto = 0;
    }//GEN-LAST:event_Prod1ActionPerformed

    private void Prod2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Prod2ActionPerformed
        // TODO add your handling code here:
        Prod1.setEnabled(false);
        Prod2.setEnabled(true);
        Prod3.setEnabled(false);
        
        tipoProducto = 1;
    }//GEN-LAST:event_Prod2ActionPerformed

    private void Prod3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Prod3ActionPerformed
        // TODO add your handling code here:
        Prod1.setEnabled(false);
        Prod2.setEnabled(false);
        Prod3.setEnabled(true);
        
        tipoProducto = 2;
    }//GEN-LAST:event_Prod3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int provIndex = selectProv.getSelectedIndex();
        Proveedor prov = this.almacen.getProveedor(provIndex);
        
        String CodProd = txtCodProd.getText();
        String DescProd = txtDescProd.getText();
        Double PrecioProd = Double.parseDouble( txtPrecioProd.getText() );
        
        Producto p = null;
        
        switch(tipoProducto) {
            case 0:
                p = new ProductoBasico( PrecioProd, DescProd, CodProd );
            case 1:
                p = new ProductoNoPerecedero( PrecioProd, DescProd, CodProd );
            case 2:
                p = new ProductoPerecedero( PrecioProd, DescProd, CodProd );
        }
        
        prov.agregarProducto(p);
        
        if( Main.MainWindow.provSeleccion == provIndex ) {
            Main.MainWindow.actualizarProductos();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Prod1;
    private javax.swing.JRadioButton Prod2;
    private javax.swing.JRadioButton Prod3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> selectProv;
    private javax.swing.JTextField txtCodProd;
    private javax.swing.JTextField txtDescProd;
    private javax.swing.JTextField txtPrecioProd;
    // End of variables declaration//GEN-END:variables
}
